### PR TITLE
Tic-Tac-Toe User Interface In Ruby

### PR DESCRIPTION
**Pull request by Paul-Clue**
## What We Did
- We completed a user interface for a tic-tac-toe game.
- We have not coded the logic of the game yet. We will do that in the next step.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required 🛑

## Hello team 👋,

**Great job on the milestone 👏. However, there are a few requirements needed before the project can be approved.**

1).**Show what message the game will inform a player if they select an invalid move.**
2).**Show how the game board will display after a player makes a move.**
3). **You have shown the winning message but not painted a scenario of how the game win looks like. Use a game board for this.**
4). **Show how a game will look using a game board when it ends in a tie, and the message the players will get to inform them of this.**
5). **The game needs a loop because there will be some repetitive tasks. Create one and add the actions needed to run inside the loop. Also, show how the loop is terminated. Check an example below**

```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

## Happy coding 🥂.

**PS: You can reach me on slack (Rose Wanjohi).**

**Comment by ixboy** [comment]
Hello TSE's
we have implemented the changes as requested, we implemented the while loop, the board shows while the game is on and it evens updates, we have even done more than what is required for the milestone two.
the game breaks because we did not create the logic yet and we will do that during milestone 3.
also we have updated the messages for the winners and a different message in case it's a draw, but many things there will be changed when we implement the logic because is very difficult to fully mock the game without the logic and the logic is only required from us during the milestone 3. Please do review our work and inform us about anything that needs to be changed or allow us to move to the next step.  Thank You...

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Status: Changes Required
Hello team,
Great work on the project so far, all your efforts are visible from the changes made but we have to make a few more changes.
REQUIRED
- [ ] If the selected move is valid, the game should display the board. But in your project, it always asks the user to enter a new valid number even if the selected move is valid.
tic1

Please fix it and ask for a new CRR!!
Keep up with the efforts towards this project, you are almost there.
Rindra Josia

**Review by mke2111 — APPROVED** [review]
# **STATUS: APPROVED**

**Congratulations Team, Keep up the high spirits and energy.** 



## **Happy coding** image

**Pull request closed without merging**
